import requests
import os
import time
import urllib.parse

def get_latest_update_id(bot_token):
    url = f"https://api.telegram.org/bot{bot_token}/getUpdates"
    try:
        res = requests.get(url).json()
        if res.get("ok") and res["result"]:
            return res["result"][-1]["update_id"]
    except:
        pass
    return None

def wait_for_user_selection(topics):
    bot_token = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")
    
    msg = "📰 *Today's Top 5 Trending Topics:*\n\n"
    for i, t in enumerate(topics, 1):
        msg += f"{i}. {t}\n\n"
    msg += "_Reply with a number (1-5) within the next 3 minutes._"
    
    requests.post(f"https://api.telegram.org/bot{bot_token}/sendMessage", json={"chat_id": chat_id, "text": msg, "parse_mode": "Markdown"})
    
    last_update_id = get_latest_update_id(bot_token)
    offset = last_update_id + 1 if last_update_id else None
    
    print("Waiting 3 minutes for user reply on Telegram...", flush=True)
    # 18 loops * 10 seconds = 3 minutes exactly
    for _ in range(18): 
        url = f"https://api.telegram.org/bot{bot_token}/getUpdates"
        if offset: url += f"?offset={offset}"
        
        try:
            res = requests.get(url).json()
            if res.get("ok") and res["result"]:
                for update in res["result"]:
                    offset = update["update_id"] + 1
                    if "message" in update and "text" in update["message"]:
                        text = update["message"]["text"].strip()
                        if text.isdigit() and 1 <= int(text) <= 5:
                            selection = topics[int(text)-1]
                            confirm_msg = f"✅ Got it! Generating 3 angles for:\n*{selection}*\n\n_Please wait ~2 minutes..._"
                            requests.post(f"https://api.telegram.org/bot{bot_token}/sendMessage", json={"chat_id": chat_id, "text": confirm_msg, "parse_mode": "Markdown"})
                            return selection
        except:
            pass
        time.sleep(10)
        
    timeout_msg = "⏱️ *3 minutes up!* Auto-selecting the top trending topic."
    requests.post(f"https://api.telegram.org/bot{bot_token}/sendMessage", json={"chat_id": chat_id, "text": timeout_msg, "parse_mode": "Markdown"})
    return topics[0]

def send_telegram_photo(bot_token, chat_id, image_url, caption):
    url = f"https://api.telegram.org/bot{bot_token}/sendPhoto"
    payload = {"chat_id": chat_id, "photo": image_url, "caption": caption, "parse_mode": "Markdown"}
    requests.post(url, json=payload)

def send_telegram_text_chunks(bot_token, chat_id, text):
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    MAX_LENGTH = 3900
    chunks = []
    current_chunk = ""
    
    for paragraph in text.split('\n'):
        if len(current_chunk) + len(paragraph) + 1 > MAX_LENGTH:
            chunks.append(current_chunk)
            current_chunk = paragraph + "\n"
        else:
            current_chunk += paragraph + "\n"
            
    if current_chunk: chunks.append(current_chunk)
        
    for chunk in chunks:
        payload = {"chat_id": chat_id, "text": chunk, "parse_mode": "Markdown"}
        res = requests.post(url, json=payload)
        # If standard markdown parsing fails, fallback to raw text (Medium still formats raw asterisks as bold!)
        if res.status_code != 200:
            payload["parse_mode"] = ""
            requests.post(url, json=payload)
        time.sleep(1)

def push_options_to_telegram(drafts):
    bot_token = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")

    for item in drafts:
        # 1. Use the custom Art Director prompt generated by the LLM
        encoded_prompt = urllib.parse.quote(item["image_prompt"])
        image_url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=1200&height=800&nologo=true"
        
        caption = f"📌 *OPTION {item['option_num']}: {item['label']}*\n\n_Download this image for the Medium header._"
        send_telegram_photo(bot_token, chat_id, image_url, caption)
        time.sleep(2)

        # 2. Send the raw, copy-paste ready article body
        send_telegram_text_chunks(bot_token, chat_id, item["body"])
        time.sleep(3)
